### ISSUE TITLE
Add GitHub Actions (CI)?

### ISSUE THREAD

**Issue by nelsonic** [indexzero/ps-tree#61]
Hi @indexzero, hope you are well. 👋 
Any objections to adding `GitHub Actions` CI so that we can:

1. Have better integration with `GitHub` and make it easier to review/approve/reject/merge PRs ... 
2. Update the version of `Node.js` to more recent versions currently: 🆕 
https://github.com/indexzero/ps-tree/blob/2b6476c837bbbd63d1a80fa8cd06adde9f4c745b/.appveyor.yml#L5-L10
3. _Actively_ test on `Windows` e.g. for: https://github.com/indexzero/ps-tree/issues/58 🪟 

Happy to pick this up and create the necessary files. 🧑‍💻 
Still have a few `JS/TS` projects and have migrated from other CI providers. 

Thoughts?

**Comment by MikeMcC399** [comment]
@nelsonic 

GitHub Actions would be a good replacement, as it offers Ubuntu, Windows (Server) and macOS runners out-of-the-box.

The following outdated CI workflows could then be removed:

- [.appveyor.yml](https://github.com/indexzero/ps-tree/blob/master/.appveyor.yml)
- [.travis.yml](https://github.com/indexzero/ps-tree/blob/master/.travis.yml)

I guess that AppVeyor would have been covering Windows CI whilst Travis would have done Linux and osx (macOS) back in the day.

Are there any active maintainers for this repo at this time i.e. who have write access to the repo and can approve / merge PRs?

**Comment by nelsonic** [comment]
@MikeMcC399 I can prepare the PR and/or merge it. :shipit:

**Comment by MikeMcC399** [comment]
@nelsonic 

If you have privileges then I suggest that you go ahead!

**Comment by MikeMcC399** [comment]
@nelsonic 

I was curious and wrote a draft workflow to be run manually. All tests pass. 🙂 

- Issue https://github.com/indexzero/ps-tree/issues/58 is not apparent on Windows Server 2022. GitHub Actions doesn't offer Windows 11 client runners to test on.

```yml
name: ci
on:
  workflow_dispatch:

jobs:

  ps-tree-ci:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 23]
        os: [ubuntu-24.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm run coverage
 
```
